export const SIGNUP_REQUEST = "USERS_SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "USERS_SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "USERS_SIGNUP_FAILURE";

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";
export const LOGOUT = "USERS_LOGOUT";

export const GET_DISTRIBUTORS_SUCCESS = "GET_DISTRIBUTORS_SUCCESS";
export const GET_DISTRIBUTORS_FAILURE = "GET_DISTRIBUTORS_FAILURE";
export const GET_SENDERS_DISTRIBUTORS = "GET_SENDERS_DISTRIBUTORS";
export const GET_SEND_ORDERS = "GET_SEND_ORDERS";

/*export const SIGNUP_REQUEST= 'USERS_SIGNUP_REQUEST',
export const   SIGNUP_SUCCESS= 'USERS_SIGNUP_SUCCESS',
export const SIGNUP_FAILURE= 'USERS_SIGNUP_FAILURE',

export const   LOGIN_REQUEST= 'USERS_LOGIN_REQUEST',
export const    LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS',
export const    LOGIN_FAILURE= 'USERS_LOGIN_FAILURE',

export const   LOGOUT= 'USERS_LOGOUT'*/
